/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drivingschool.GUI;

import drivingschool.repo.PaymentRepo;

import drivingschool.entity.Payment;
import drivingschool.repo.PaymentModel;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dovud Inomov
 */
public class JFrame_PaymentAdd extends javax.swing.JFrame {

    public Boolean isEdit;
    public int selected_id;
    private final PaymentModel pModel;

    /**
     * Creates new form JFrame_StudentAdd
     */
    public JFrame_PaymentAdd() {
        initComponents();
        isEdit = false;
        pModel = new PaymentModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        stdIDLabel = new javax.swing.JLabel();
        stdIDTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        commentLabel = new javax.swing.JLabel();
        commentTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Payment data");
        setName("frame_StudentAdd"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDLabel.setText("ID");

        IDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDTextField.setName("jTextFiend_StdNo"); // NOI18N
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });

        stdIDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdIDLabel.setText("Stident ID");

        stdIDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdIDTextField.setName("jTextField_Name"); // NOI18N
        stdIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIDTextFieldActionPerformed(evt);
            }
        });

        amountLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountLabel.setText("Amount");

        amountTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountTextField.setToolTipText("");
        amountTextField.setName("jTextField_Surname"); // NOI18N
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });

        commentLabel.setText("Comment");

        commentTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        commentTextField.setInheritsPopupMenu(true);
        commentTextField.setName("jTextField_Nationality"); // NOI18N

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drivingschool/assets/iconfinder_Save_132607.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setName("jButton_Save"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdIDLabel)
                    .addComponent(amountLabel)
                    .addComponent(commentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(IDTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(stdIDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(amountTextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(saveButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdIDLabel)
                    .addComponent(stdIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountLabel)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentLabel)
                    .addComponent(commentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(saveButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusLost

    }//GEN-LAST:event_IDTextFieldFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!stdIDTextField.getText().trim().isEmpty() && !amountTextField.getText().trim().isEmpty()) {
            int stdID = Integer.valueOf(stdIDTextField.getText().trim());
            double amount = Double.valueOf(amountTextField.getText().trim());
            String comment = commentTextField.getText().trim();

            if (!isEdit) {
                pModel.addPayment(stdID, amount, comment);
                JOptionPane.showMessageDialog(null, "The New Payment Data is Recorded Successfully");
            } else {
                if (!IDTextField.getText().trim().isEmpty()) {
                    int id = Integer.valueOf(IDTextField.getText().trim());
                    pModel.editPayment(id, stdID, amount, comment);
                    JOptionPane.showMessageDialog(null, "The Selected Payment Data is Edited Successfully");
                }
            }
            setVisible(false);
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (isEdit) {
            Payment p = pModel.getPaymentById(selected_id);

            IDTextField.setText(String.valueOf(p.getID()));
            stdIDTextField.setText(String.valueOf(p.getStudentID()));
            amountTextField.setText(String.valueOf(p.getAmount()));
            commentTextField.setText(p.getComment());
        }
    }//GEN-LAST:event_formWindowActivated

    private void stdIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdIDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_PaymentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_PaymentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_PaymentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_PaymentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_PaymentAdd().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JTextField commentTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel stdIDLabel;
    private javax.swing.JTextField stdIDTextField;
    // End of variables declaration//GEN-END:variables
}
