/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drivingschool.GUI;

import drivingschool.repo.AgreementRepo;

import drivingschool.entity.Agreement;
import drivingschool.entity.CoursePackage;
import drivingschool.repo.PackageRepo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dovud Inomov
 */
public class JFrame_AgreementAdd extends javax.swing.JFrame {

    public Boolean isEdit;
    public int st_row;

    /**
     * Creates new form JFrame_StudentAdd
     */
    public JFrame_AgreementAdd() {
        initComponents();
        isEdit = false;

        // Populate dropdown with values
        for (int i = 0; i < PackageRepo.packages.size(); i++) {
            CoursePackage p = (CoursePackage) PackageRepo.packages.get(i);
            if (!p.getName().isEmpty()) {
                pkgComboBox.addItem(p.getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        stdIDLabel = new javax.swing.JLabel();
        stdIDTextField = new javax.swing.JTextField();
        pkgIDLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        pkgComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter The Information Of The Student");
        setName("frame_StudentAdd"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDLabel.setText("ID");

        IDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDTextField.setName("jTextFiend_StdNo"); // NOI18N
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });

        stdIDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdIDLabel.setText("Stident ID");

        stdIDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdIDTextField.setName("jTextField_Name"); // NOI18N
        stdIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIDTextFieldActionPerformed(evt);
            }
        });

        pkgIDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pkgIDLabel.setText("Package ID");

        startDateLabel.setText("Start Date");

        startDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDateTextField.setInheritsPopupMenu(true);
        startDateTextField.setName("jTextField_Nationality"); // NOI18N

        saveButton.setText("Save");
        saveButton.setName("jButton_Save"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        pkgComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pkgComboBoxItemStateChanged(evt);
            }
        });
        pkgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkgComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdIDLabel)
                    .addComponent(pkgIDLabel)
                    .addComponent(startDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stdIDTextField)
                        .addComponent(pkgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdIDLabel)
                    .addComponent(stdIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pkgIDLabel)
                    .addComponent(pkgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel))
                .addGap(63, 63, 63)
                .addComponent(saveButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusLost

    }//GEN-LAST:event_IDTextFieldFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!IDTextField.getText().trim().isEmpty()
                && !stdIDTextField.getText().trim().isEmpty()
                && !pkgIdValue.trim().isEmpty()
                && !startDateTextField.getText().trim().isEmpty()) {
            String id = IDTextField.getText().trim();
            String stdID = stdIDTextField.getText().trim();
            String pkgID = pkgIdValue.trim();
            String startDate = startDateTextField.getText().trim();

            if (!isEdit) {
                AgreementRepo.addAgreement(id, stdID, pkgID, startDate);
                JOptionPane.showMessageDialog(null,
                        "The New Agreement Data is Recorded Successfully");
            } else {
                AgreementRepo.editAgreement(id, stdID, pkgID, startDate);
                JOptionPane.showMessageDialog(null, "The Selected Agreement Data is Edited Successfully");
            }
            try {
                AgreementRepo.listAgreements();
            } catch (IOException ex) {
                Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);

        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (isEdit) {
            Agreement ag = (Agreement) AgreementRepo.agreements.get(st_row);
            IDTextField.setText(ag.getID());
            stdIDTextField.setText(ag.getStudentID());
            pkgIdValue = ag.getPackageID();
            startDateTextField.setText(ag.getStartDate().toString());
        }
    }//GEN-LAST:event_formWindowActivated

    private void stdIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdIDTextFieldActionPerformed

    private void pkgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkgComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pkgComboBoxActionPerformed

    private void pkgComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pkgComboBoxItemStateChanged
        String selectedPkg = (String) pkgComboBox.getSelectedItem();
        String selectedID = PackageRepo.getIDByName(selectedPkg);
        pkgIdValue = selectedID;
    }//GEN-LAST:event_pkgComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_AgreementAdd().setVisible(true);

            }
        });
    }

    private String pkgIdValue;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> pkgComboBox;
    private javax.swing.JLabel pkgIDLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JLabel stdIDLabel;
    private javax.swing.JTextField stdIDTextField;
    // End of variables declaration//GEN-END:variables
}
