/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drivingschool.GUI;


import drivingschool.entity.Agreement;
import drivingschool.repo.AgreementModel;

import javax.swing.JOptionPane;

/**
 *
 * @author Dovud Inomov
 */
public class JFrame_AgreementAdd extends javax.swing.JFrame {

    public Boolean isEdit;
    public int selected_id;
    private final AgreementModel aModel;

    /**
     * Creates new form JFrame_StudentAdd
     */
    public JFrame_AgreementAdd() {
        initComponents();
        isEdit = false;
        aModel = new AgreementModel();

        // Populate dropdown with values
//        for (int i = 0; i < PackageRepo.packages.size(); i++) {
//            CoursePackage dept = (CoursePackage) PackageRepo.packages.get(i);
//            if (!dept.getName().isEmpty()) {
//                pkgComboBox.addItem(dept.getName());
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        stdIDLabel = new javax.swing.JLabel();
        stdIDTextField = new javax.swing.JTextField();
        pkgIDLabel = new javax.swing.JLabel();
        pkgIDTextField = new javax.swing.JTextField();
        startDateLabel = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter The Information Of The Agreement");
        setName("frame_StudentAdd"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDLabel.setText("ID");

        IDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDTextField.setName("jTextFiend_StdNo"); // NOI18N
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });

        stdIDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdIDLabel.setText("Stident ID");

        stdIDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdIDTextField.setName("jTextField_Name"); // NOI18N
        stdIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIDTextFieldActionPerformed(evt);
            }
        });

        pkgIDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pkgIDLabel.setText("Package ID");

        pkgIDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pkgIDTextField.setToolTipText("");
        pkgIDTextField.setName("jTextField_Surname"); // NOI18N
        pkgIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkgIDTextFieldActionPerformed(evt);
            }
        });

        startDateLabel.setText("Start Date (yyyy-mm-dd)");

        startDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDateTextField.setInheritsPopupMenu(true);
        startDateTextField.setName("jTextField_Nationality"); // NOI18N

        saveButton.setText("Save");
        saveButton.setName("jButton_Save"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stdIDLabel)
                        .addComponent(pkgIDLabel)
                        .addComponent(startDateLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pkgIDTextField)
                    .addComponent(stdIDTextField)
                    .addComponent(IDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(startDateTextField))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdIDLabel)
                    .addComponent(stdIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pkgIDLabel)
                    .addComponent(pkgIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusLost

    }//GEN-LAST:event_IDTextFieldFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!stdIDTextField.getText().trim().isEmpty()
                && !pkgIDTextField.getText().trim().isEmpty()
                && !startDateTextField.getText().trim().isEmpty()) {
            int stdID = Integer.valueOf(stdIDTextField.getText().trim());
            int pkgID = Integer.valueOf(pkgIDTextField.getText().trim());
            String startDate = startDateTextField.getText().trim();

            if (!isEdit) {
                aModel.addAgreement(stdID, pkgID, startDate);
                JOptionPane.showMessageDialog(null,
                        "The New Agreement Data is Recorded Successfully");
            } else {
                if (!IDTextField.getText().trim().isEmpty()) {
                    int id = Integer.valueOf(IDTextField.getText().trim());

                    aModel.editAgreement(id, stdID, pkgID, startDate);
                    JOptionPane.showMessageDialog(null, "The Selected Agreement Data is Edited Successfully");
                }
            }
//            AgreementRepo.listAgreements();
            setVisible(false);

        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (isEdit) {
            Agreement ag = aModel.getAgreementById(selected_id);

            IDTextField.setText(String.valueOf(ag.getID()));
            stdIDTextField.setText(String.valueOf(ag.getStudentID()));
            pkgIDTextField.setText(String.valueOf(ag.getPackageID()));
            startDateTextField.setText(ag.getStartDate());
        }
    }//GEN-LAST:event_formWindowActivated

    private void stdIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdIDTextFieldActionPerformed

    private void pkgIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkgIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pkgIDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgreementAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_AgreementAdd().setVisible(true);

            }
        });
    }
    private String pkgIdValue;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel pkgIDLabel;
    private javax.swing.JTextField pkgIDTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JLabel stdIDLabel;
    private javax.swing.JTextField stdIDTextField;
    // End of variables declaration//GEN-END:variables
}
