/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drivingschool.GUI;

import drivingschool.repo.LessonRepo;

import drivingschool.entity.Lesson;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dovud Inomov
 */
public class JFrame_LessonAdd extends javax.swing.JFrame {

    public Boolean isEdit;
    public int st_row;

    /**
     * Creates new form JFrame_StudentAdd
     */
    public JFrame_LessonAdd() {
        initComponents();
        isEdit = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        stdNoLabel = new javax.swing.JLabel();
        stdIDTextField = new javax.swing.JTextField();
        packageIDLabel = new javax.swing.JLabel();
        packageIDTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        startTimeLabel = new javax.swing.JLabel();
        startTimeTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        gradeTextField = new javax.swing.JTextField();
        gradeLabe = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        endTimeLabel = new javax.swing.JLabel();
        endTimeTextField = new javax.swing.JTextField();
        lessonNoTextField = new javax.swing.JTextField();
        lessonNoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a new lesson");
        setName("frame_StudentAdd"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        stdNoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdNoLabel.setText("Std ID");

        stdIDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stdIDTextField.setName("jTextFiend_StdNo"); // NOI18N
        stdIDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdIDTextFieldFocusLost(evt);
            }
        });

        packageIDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        packageIDLabel.setText("Package ID");

        packageIDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        packageIDTextField.setName("jTextField_Name"); // NOI18N

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateLabel.setText("Date");

        dateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateTextField.setToolTipText("");
        dateTextField.setName("jTextField_Surname"); // NOI18N
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        startTimeLabel.setText("Start time");

        startTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startTimeTextField.setName("jTextField_Birthday"); // NOI18N
        startTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeTextFieldActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drivingschool/assets/iconfinder_Save_132607.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setName("jButton_Save"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        gradeTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gradeTextField.setName("jTextField_Birthday"); // NOI18N

        gradeLabe.setText("Grade");

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDLabel.setText("ID");

        IDTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDTextField.setName("jTextFiend_StdNo"); // NOI18N
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });

        endTimeLabel.setText("End time");

        endTimeTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        endTimeTextField.setName("jTextField_Birthday"); // NOI18N
        endTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTimeTextFieldActionPerformed(evt);
            }
        });

        lessonNoTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lessonNoTextField.setName("jTextField_Name"); // NOI18N

        lessonNoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lessonNoLabel.setText("Lesson No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stdNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(packageIDLabel)
                                    .addComponent(lessonNoLabel)
                                    .addComponent(gradeLabe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lessonNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(stdIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                                .addComponent(packageIDTextField)))
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateLabel)
                                            .addComponent(startTimeLabel)
                                            .addComponent(startTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(gradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(saveButton)
                                        .addGap(45, 45, 45)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endTimeLabel))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel)
                            .addComponent(startTimeLabel)
                            .addComponent(endTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdNoLabel)
                            .addComponent(stdIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(packageIDLabel)
                            .addComponent(packageIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel)
                            .addComponent(lessonNoLabel)
                            .addComponent(lessonNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradeLabe)
                        .addGap(6, 6, 6))
                    .addComponent(gradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(saveButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void stdIDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdIDTextFieldFocusLost

    }//GEN-LAST:event_stdIDTextFieldFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!stdIDTextField.getText().trim().isEmpty()
                && !packageIDTextField.getText().trim().isEmpty()
                && !dateTextField.getText().trim().isEmpty()
                && !endTimeTextField.getText().trim().isEmpty()
                && !lessonNoTextField.getText().trim().isEmpty()
                && !gradeTextField.getText().trim().isEmpty()
                && !IDTextField.getText().trim().isEmpty()
                && !startTimeTextField.getText().trim().isEmpty()) {
            String id = IDTextField.getText().trim();
            String std_no = stdIDTextField.getText().trim();
            String pkg_id = packageIDTextField.getText().trim();
            String lesson_no = lessonNoTextField.getText().trim();
            String date = dateTextField.getText().trim();
            String end_time = endTimeTextField.getText().trim();
            String start_time = startTimeTextField.getText().trim();
            String grade = gradeTextField.getText().trim();

            if (!isEdit) {
                LessonRepo.addLesson(id, pkg_id, std_no, Integer.parseInt(lesson_no), date, start_time, end_time, Integer.parseInt(grade));
                JOptionPane.showMessageDialog(null,
                        "The New Lesson Data is Recorded Successfully");
            } else {
                LessonRepo.editLesson(id, pkg_id, std_no, Integer.parseInt(lesson_no), date, start_time, end_time, Integer.parseInt(grade));
                JOptionPane.showMessageDialog(null, "The Selected Lesson Data is Edited Successfully");
            }
            try {
                LessonRepo.listLessons();
            } catch (IOException ex) {
                Logger.getLogger(JFrame_LessonAdd.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JFrame_LessonAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);

        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (isEdit) {
            Lesson st = (Lesson) LessonRepo.lessons.get(st_row);
            IDTextField.setText(st.getID());
            stdIDTextField.setText(st.getStudentID());
            packageIDTextField.setText(st.getPackageID());
            lessonNoTextField.setText(String.valueOf(st.getLessonNo()));
            dateTextField.setText(st.getLessonDate().toString());
            startTimeTextField.setText(st.getStartTime());
            endTimeTextField.setText(st.getEndTime());
            gradeTextField.setText(Integer.toString(st.getGrade()));

        }
    }//GEN-LAST:event_formWindowActivated

    private void startTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTimeTextFieldActionPerformed

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldFocusLost

    private void endTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTimeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_LessonAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_LessonAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_LessonAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_LessonAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_LessonAdd().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel endTimeLabel;
    private javax.swing.JTextField endTimeTextField;
    private javax.swing.JLabel gradeLabe;
    private javax.swing.JTextField gradeTextField;
    private javax.swing.JLabel lessonNoLabel;
    private javax.swing.JTextField lessonNoTextField;
    private javax.swing.JLabel packageIDLabel;
    private javax.swing.JTextField packageIDTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JTextField startTimeTextField;
    private javax.swing.JTextField stdIDTextField;
    private javax.swing.JLabel stdNoLabel;
    // End of variables declaration//GEN-END:variables
}
