/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drivingschool.GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import drivingschool.repo.AgreementRepo;
import drivingschool.repo.LessonRepo;
import drivingschool.repo.PackageRepo;
import drivingschool.repo.PaymentRepo;
import drivingschool.repo.StudentRepo;

/**
 *
 * @author btyo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        systemMenu = new javax.swing.JMenu();
        testBtn = new javax.swing.JMenuItem();
        backupBtn = new javax.swing.JMenuItem();
        restoreBtn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        quitBtn = new javax.swing.JMenuItem();
        studentsMenu = new javax.swing.JMenu();
        addStudentBtn = new javax.swing.JMenuItem();
        listStudentsBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        listDeptBtn = new javax.swing.JMenuItem();
        addLessonBtn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        listCourseBtn = new javax.swing.JMenuItem();
        addPackagesBtn = new javax.swing.JMenuItem();
        gradesMenu = new javax.swing.JMenu();
        listPaymentsBtn = new javax.swing.JMenuItem();
        addPaymentBtn = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        listAgmtBtn = new javax.swing.JMenuItem();
        addAgmtBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        systemMenu.setText("System");

        testBtn.setText("Run tests");
        testBtn.setName("jMenuItem_Restore"); // NOI18N
        testBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnActionPerformed(evt);
            }
        });
        systemMenu.add(testBtn);

        backupBtn.setText("Backup");
        backupBtn.setName("jMenuItem_backup"); // NOI18N
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });
        systemMenu.add(backupBtn);

        restoreBtn.setText("Restore");
        restoreBtn.setName("jMenuItem_Restore"); // NOI18N
        restoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreBtnActionPerformed(evt);
            }
        });
        systemMenu.add(restoreBtn);
        systemMenu.add(jSeparator1);

        quitBtn.setText("Quit");
        quitBtn.setName("jMenuItem_Quit"); // NOI18N
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });
        systemMenu.add(quitBtn);

        jMenuBar1.add(systemMenu);

        studentsMenu.setText("Students");

        addStudentBtn.setText("Add Student");
        addStudentBtn.setName("jMenuItem_AddStudent"); // NOI18N
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });
        studentsMenu.add(addStudentBtn);

        listStudentsBtn.setText("List Students");
        listStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentsBtnActionPerformed(evt);
            }
        });
        studentsMenu.add(listStudentsBtn);

        jMenuBar1.add(studentsMenu);

        jMenu3.setText("Lessons");

        listDeptBtn.setText("View Lessons");
        listDeptBtn.setName(""); // NOI18N
        listDeptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDeptBtnActionPerformed(evt);
            }
        });
        jMenu3.add(listDeptBtn);

        addLessonBtn.setText("New Lesson");
        addLessonBtn.setName("jMenuItem_AddDepartment"); // NOI18N
        addLessonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonBtnActionPerformed(evt);
            }
        });
        jMenu3.add(addLessonBtn);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Packages");

        listCourseBtn.setText("List Packages");
        listCourseBtn.setName(""); // NOI18N
        listCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCourseBtnActionPerformed(evt);
            }
        });
        jMenu4.add(listCourseBtn);

        addPackagesBtn.setText("Add Package");
        addPackagesBtn.setName("jMenuItem_AddDepartment"); // NOI18N
        addPackagesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPackagesBtnActionPerformed(evt);
            }
        });
        jMenu4.add(addPackagesBtn);

        jMenuBar1.add(jMenu4);

        gradesMenu.setText("Payment");
        gradesMenu.setName("jMenu_Grades"); // NOI18N

        listPaymentsBtn.setText("List Payments");
        listPaymentsBtn.setName(""); // NOI18N
        listPaymentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPaymentsBtnActionPerformed(evt);
            }
        });
        gradesMenu.add(listPaymentsBtn);

        addPaymentBtn.setText("New Payment");
        addPaymentBtn.setName("jMenuItem_AddDepartment"); // NOI18N
        addPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentBtnActionPerformed(evt);
            }
        });
        gradesMenu.add(addPaymentBtn);

        jMenuBar1.add(gradesMenu);

        jMenu6.setText("Agreements");
        jMenu6.setName("JMenu_Attendance"); // NOI18N

        listAgmtBtn.setText("List Agreements");
        listAgmtBtn.setName(""); // NOI18N
        listAgmtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAgmtBtnActionPerformed(evt);
            }
        });
        jMenu6.add(listAgmtBtn);

        addAgmtBtn.setText("Add Agreement");
        addAgmtBtn.setName("jMenuItem_AddDepartment"); // NOI18N
        addAgmtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAgmtBtnActionPerformed(evt);
            }
        });
        jMenu6.add(addAgmtBtn);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreBtnActionPerformed
        try {
            StudentRepo.retrieveStudent();
//            DepartmentsRepo.retrieveDepartment();
//            CourseRepo.retrieveCourse();
//            AttendanceRepo.retrieveAttendance();
//            GradesRepo.retrieveGrade();

            JOptionPane.showMessageDialog(null, "Data Successfully Retrieved");
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_restoreBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBtnActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
         new JFrame_StudentAdd().show();
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void listStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentsBtnActionPerformed
        new JFrame_StudentList().show();
    }//GEN-LAST:event_listStudentsBtnActionPerformed

    private void listDeptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDeptBtnActionPerformed
//        new JFrame_DepartmentList().show();
    }//GEN-LAST:event_listDeptBtnActionPerformed

    private void addLessonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonBtnActionPerformed
//        new JFrame_DepartmentAdd().show();
    }//GEN-LAST:event_addLessonBtnActionPerformed

    private void listCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCourseBtnActionPerformed
//        new JFrame_CourseList().show();
    }//GEN-LAST:event_listCourseBtnActionPerformed

    private void addPackagesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPackagesBtnActionPerformed
//        new JFrame_CourseAdd().show();

    }//GEN-LAST:event_addPackagesBtnActionPerformed

    private void listPaymentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPaymentsBtnActionPerformed
//        new JFrame_GradeList().show();
    }//GEN-LAST:event_listPaymentsBtnActionPerformed

    private void addPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentBtnActionPerformed
//        new JFrame_GradeAdd().show();
    }//GEN-LAST:event_addPaymentBtnActionPerformed

    private void listAgmtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAgmtBtnActionPerformed
//        new JFrame_AttendanceList().show();
    }//GEN-LAST:event_listAgmtBtnActionPerformed

    private void addAgmtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAgmtBtnActionPerformed
//        new JFrame_AttendanceAdd().show();
    }//GEN-LAST:event_addAgmtBtnActionPerformed

    private void testBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnActionPerformed
        drivingschool.DrivingSchool.populateAllData();
    }//GEN-LAST:event_testBtnActionPerformed

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        try {
            StudentRepo.backupStudent();
            //            DepartmentsRepo.backupDepartment();
            JOptionPane.showMessageDialog(null, "Data Successfully Backuped");
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAgmtBtn;
    private javax.swing.JMenuItem addLessonBtn;
    private javax.swing.JMenuItem addPackagesBtn;
    private javax.swing.JMenuItem addPaymentBtn;
    private javax.swing.JMenuItem addStudentBtn;
    private javax.swing.JMenuItem backupBtn;
    private javax.swing.JMenu gradesMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem listAgmtBtn;
    private javax.swing.JMenuItem listCourseBtn;
    private javax.swing.JMenuItem listDeptBtn;
    private javax.swing.JMenuItem listPaymentsBtn;
    private javax.swing.JMenuItem listStudentsBtn;
    private javax.swing.JMenuItem quitBtn;
    private javax.swing.JMenuItem restoreBtn;
    private javax.swing.JMenu studentsMenu;
    private javax.swing.JMenu systemMenu;
    private javax.swing.JMenuItem testBtn;
    // End of variables declaration//GEN-END:variables
}
